---
- hosts: docker.yourdomain.org
  become: true

  vars:
       owneracct: root

  tasks:

    - name: Create base directory
      file:
        path: /var/containerdata
        state: directory
        owner: "{{ owneracct }}"
        group: root
        mode: 0755

    - name: Create rsa_ocsp directory
      file:
        path: /var/containerdata/rsa_ocsp        
        state: directory
        owner: "{{ owneracct }}"
        group: root
        mode: 0755

    - name: Create nginx_crl directory
      file:
        path: /var/containerdata/nginx_crl
        state: directory
        owner: "{{ owneracct }}"
        group: root
        mode: 0755

    - name: Create nginx_crl config directory
      file:
        path: /var/containerdata/nginx_crl/config
        state: directory
        owner: "{{ owneracct }}"
        group: root
        mode: 0755

    - name: Create nginx_crl content directory
      file:
        path: /var/containerdata/nginx_crl/content
        state: directory
        owner: "{{ owneracct }}"
        group: root
        mode: 0755

    - name: Create nginx_crl log directory
      file:
        path: /var/containerdata/nginx_crl/log
        state: directory
        owner: "{{ owneracct }}"
        group: root
        mode: 0755

    - name: Download nginx config file
      get_url:
        url: https://raw.githubusercontent.com/mattbodholdt/OpenSSLCA/master/NGINX/nginx.conf
        dest: /var/containerdata/nginx_crl/config/nginx.conf
        owner: "{{ owneracct }}"
        mode: 0644

    - name: Download nginx mime type file
      get_url:
        url: https://raw.githubusercontent.com/mattbodholdt/OpenSSLCA/master/NGINX/mime.types
        dest: /var/containerdata/nginx_crl/config/mime.types
        owner: "{{ owneracct }}"
        mode: 0644

    - name: Copy RSA Root CRL
      copy:
        src: /root/ca_rsa/crl/rootcrl.crl
        dest: /var/containerdata/nginx_crl/content/rootcrl.crl
        owner: "{{ owneracct }}"
        group: root
        mode: 0644

    - name: Copy RSA Intermediate CRL                          
      copy:
        src: /root/ca_rsa/intermediate/crl/intcrl.crl   
        dest: /var/containerdata/nginx_crl/content/intcrl.crl
        owner: "{{ owneracct }}"
        group: root
        mode: 0644

    - name: Copy RSA Root Cert
      copy:
        src: /root/ca_rsa/certs/ca.root.crt.pem
        dest: /var/containerdata/nginx_crl/content/root.crt
        owner: "{{ owneracct }}"
        group: root
        mode: 0644

    - name: Copy RSA Intermediate Cert
      copy:
        src: /root/ca_rsa/intermediate/certs/int.ca.crt.pem
        dest: /var/containerdata/nginx_crl/content/int.crt
        owner: "{{ owneracct }}"
        group: root
        mode: 0644

    - name: Copy CA Chain
      copy:
        src: /root/ca_rsa/intermediate/certs/rsa_ca_chain.pem
        dest: /var/containerdata/rsa_ocsp/rsa_ca_chain.pem
        owner: "{{ owneracct }}"
        group: root
        mode: 0644

    - name: Copy OCSP Key                              
      copy:
        src: /root/ca_rsa/intermediate/private/ocsp_rsa_key_rp.pem    
        dest: /var/containerdata/rsa_ocsp/ocsp_rsa.pem
        owner: "{{ owneracct }}"
        group: root
        mode: 0644

    - name: Copy OCSP Certificate
      copy:
        src: /root/ca_rsa/intermediate/certs/ocsp_rsa_cert.pem
        dest: /var/containerdata/rsa_ocsp/rsa_ocsp_cert.pem
        owner: "{{ owneracct }}"
        group: root
        mode: 0644

    - name: Copy RSA CA Index
      copy:
        src: /root/ca_rsa/intermediate/index.txt
        dest: /var/containerdata/rsa_ocsp/index.txt
        owner: "{{ owneracct }}"
        group: root
        mode: 0644
